FROM node:16-alpine3.14 AS builder
WORKDIR /app
# ENV
ARG REACT_APP_ENV
ENV REACT_APP_ENV $REACT_APP_ENV
# END OF ENV

COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . ./
RUN yarn build

FROM nginx:1.21.6-alpine AS server
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder ./app/build /usr/share/nginx/html